# S3 bucket for hosting product images
# Images will be publicly accessible for the web application
# This is always created when deploying to AWS
# For local development, the Flask app serves images from infrastructure/images/

resource "aws_s3_bucket" "product_images" {
  bucket = "${local.name_prefix}-product-images"

  tags = merge(local.common_tags, {
    Name = "${local.name_prefix}-product-images"
  })
}

# Enable versioning for the bucket (optional but recommended)
resource "aws_s3_bucket_versioning" "product_images" {
  bucket = aws_s3_bucket.product_images.id

  versioning_configuration {
    status = "Enabled"
  }
}

# Block ALL public access - bucket is completely private
resource "aws_s3_bucket_public_access_block" "product_images" {
  bucket = aws_s3_bucket.product_images.id

  block_public_acls       = true
  block_public_policy     = true   # Block all public bucket policies
  ignore_public_acls      = true
  restrict_public_buckets = true   # Restrict all public bucket access
}

# Bucket policy to allow access ONLY from EC2 instances with the LabRole
# Images can only be accessed via signed URLs generated by the Flask app
resource "aws_s3_bucket_policy" "product_images" {
  bucket = aws_s3_bucket.product_images.id

  # Wait for public access block to be configured first
  depends_on = [aws_s3_bucket_public_access_block.product_images]

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "AllowEC2InstanceAccess"
        Effect = "Allow"
        Principal = {
          AWS = data.aws_iam_role.ec2_role.arn
        }
        Action = [
          "s3:GetObject",
          "s3:ListBucket"
        ]
        Resource = [
          "${aws_s3_bucket.product_images.arn}",
          "${aws_s3_bucket.product_images.arn}/*"
        ]
      }
    ]
  })
}

# CORS configuration for web access
resource "aws_s3_bucket_cors_configuration" "product_images" {
  bucket = aws_s3_bucket.product_images.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "HEAD"]
    allowed_origins = ["*"]  # In production, restrict to your domain
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}

# Lifecycle rule to manage old versions (optional)
resource "aws_s3_bucket_lifecycle_configuration" "product_images" {
  bucket = aws_s3_bucket.product_images.id

  rule {
    id     = "delete-old-versions"
    status = "Enabled"

    noncurrent_version_expiration {
      noncurrent_days = 90
    }
  }
}

# Output the bucket name for Flask to use when generating signed URLs
# Note: We don't output a direct URL since the bucket is private
locals {
  s3_bucket_name = aws_s3_bucket.product_images.id
}
